//
// Created by bensoer on 04/02/16.
//

#ifndef INC_8005_A2_SCALABLESERVERS_CONNECTIONRECORD_H
#define INC_8005_A2_SCALABLESERVERS_CONNECTIONRECORD_H


class ConnectionRecord {

};


#endif //INC_8005_A2_SCALABLESERVERS_CONNECTIONRECORD_H
