//
// Created by bensoer on 05/02/16.
//

#ifndef INC_8005_A2_SCALABLESERVERS_ECHOPROCESS_H
#define INC_8005_A2_SCALABLESERVERS_ECHOPROCESS_H


class EchoProcess {

};


#endif //INC_8005_A2_SCALABLESERVERS_ECHOPROCESS_H
